config: 
# Concat
  concat: 
    namejs: addons
    namecss: addons
    js: 
      - "bower_components/jquery/dist/jquery.js"
    css: 
      - "bower_components/animate.css/animate.css"
# Base config
  url: "./"
  source: "src"
  views: "src/views"
  dest: "dist"
  tmp: "tmp"
  docs: "docs"
  test: "test"
  resources: "resources"
  config: "config"
  fonts: "fonts"
  data: "data"
  blank: "_blank"
  images: "img"
# Layout
  layouts: 
    assets: "partials"
    root: "templates"
    jade: "templates/jade-pug"
    nunjucks: "templates/nunjucks"
# Scripts
  scripts: 
    assets: "js"
    root: "scripts"
    typescript: "scripts/typescript"
    javascript: "scripts/js"
    coffee: "scripts/coffee"
# Styles
  styles: 
    assets: "css"
    root: "styles"
    css: "styles/css"
    less: "styles/less"
    sass: "styles/sass"
    stylus: "styles/stylus"
# Ignore
  ignore: 
    copy: "{**/*.jade,**/*.njk,**/*.js,**/*.ts,**/*.coffee}"
    scripts: "{**/*.ts,**/*.coffee}"
    jade: "{include,include/**}"
    nunjucks: "{include,include/**}"
    sass: "{include,include/**}"
    stylus: "{include,include/**}"
    css: "{include,include/**}"
    less: "{include,include/**}"
    test: "{vendor,vendor/**}"
# Config Host
  host: "127.0.0.1"
  port: "8888"
# Packer
  packer: main.js
  packerdist: app.js #to app.min.js
# License
  title: "Gulp App"
  author: 
    email: "baonguyenyam@gmail.com"
    name: "BaoNguyen"
    link: "https://github.com/baonguyenyam"
    coding: "Coding by Bao Nguyen"
  license: "MIT"
  name: "Bao Nguyen Apps"
  version: "1.0"
# SEO
  SEO:
    AppName: "WebApp"
    cfg_name: "Bao Nguyen"
    analytics: 'UA-79215807-1'
    app_appleID: '12345678'
    seo_geo: 'VN-64'
    seo_geo_lng: '106.673089'
    seo_geo_dlg: '10.359352'
    app_facebook_adminsID: 'XXXXXXX,XXXXXXX'
    app_facebook_ID: '100000511421818'
    cfg_description: "I’ve been designing profesionally since 2003. I founded GC Com in 2008."
    cfg_keywords: "Bao Nguyen, Bảo Nguyên, Brands Designer, Web Developer, Apps Developer, Photograper, Front-End Developer"
    cfg_title: "Bao Nguyen - Bảo Nguyên - Brands Designer/Web Developer/Apps Developer/Photograper/Front-End Developer"
    cfg_content: "Brands Designer/Web Developer/Apps Developer/Photograper/Front-End Developer"
    cfg_author: "Bao Nguyen"
    cfg_url: "baonguyenyam.github.io"
    cfg_sitenameurl: "baonguyenyam" 